# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_appointment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateAppointmentForm(object):
    def setupUi(self, CreateAppointmentForm):
        CreateAppointmentForm.setObjectName("CreateAppointmentForm")
        CreateAppointmentForm.resize(351, 305)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateAppointmentForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(CreateAppointmentForm)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.patientCombobox = QtWidgets.QComboBox(CreateAppointmentForm)
        self.patientCombobox.setObjectName("patientCombobox")
        self.horizontalLayout_9.addWidget(self.patientCombobox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(CreateAppointmentForm)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.doctorCombobox = QtWidgets.QComboBox(CreateAppointmentForm)
        self.doctorCombobox.setObjectName("doctorCombobox")
        self.horizontalLayout_10.addWidget(self.doctorCombobox)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(CreateAppointmentForm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QLineEdit(CreateAppointmentForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(CreateAppointmentForm)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.statusEdit = QtWidgets.QLineEdit(CreateAppointmentForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusEdit.sizePolicy().hasHeightForWidth())
        self.statusEdit.setSizePolicy(sizePolicy)
        self.statusEdit.setObjectName("statusEdit")
        self.horizontalLayout_4.addWidget(self.statusEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(CreateAppointmentForm)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.remarkEdit = QtWidgets.QTextEdit(CreateAppointmentForm)
        self.remarkEdit.setObjectName("remarkEdit")
        self.verticalLayout_4.addWidget(self.remarkEdit)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateAppointmentForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CreateAppointmentForm)
        self.buttonBox.accepted.connect(CreateAppointmentForm.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateAppointmentForm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateAppointmentForm)

    def retranslateUi(self, CreateAppointmentForm):
        _translate = QtCore.QCoreApplication.translate
        CreateAppointmentForm.setWindowTitle(_translate("CreateAppointmentForm", "Dialog"))
        self.label_9.setText(_translate("CreateAppointmentForm", "Пациент"))
        self.label_10.setText(_translate("CreateAppointmentForm", "Доктор"))
        self.label_3.setText(_translate("CreateAppointmentForm", "Дата и время"))
        self.dateEdit.setToolTip(_translate("CreateAppointmentForm", "31.12.2004 17:30"))
        self.label_4.setText(_translate("CreateAppointmentForm", "Статус"))
        self.statusEdit.setText(_translate("CreateAppointmentForm", "Запланировано"))
        self.label_7.setText(_translate("CreateAppointmentForm", "Примечание"))
