# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'id_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatePatientForm(object):
    def setupUi(self, CreatePatientForm):
        CreatePatientForm.setObjectName("CreatePatientForm")
        CreatePatientForm.resize(184, 81)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreatePatientForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CreatePatientForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.idEdit = QtWidgets.QLineEdit(CreatePatientForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idEdit.sizePolicy().hasHeightForWidth())
        self.idEdit.setSizePolicy(sizePolicy)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout.addWidget(self.idEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreatePatientForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CreatePatientForm)
        self.buttonBox.accepted.connect(CreatePatientForm.accept) # type: ignore
        self.buttonBox.rejected.connect(CreatePatientForm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreatePatientForm)

    def retranslateUi(self, CreatePatientForm):
        _translate = QtCore.QCoreApplication.translate
        CreatePatientForm.setWindowTitle(_translate("CreatePatientForm", "Dialog"))
        self.label.setText(_translate("CreatePatientForm", "ID"))
