# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appointmentsTable = QtWidgets.QTabWidget(self.centralwidget)
        self.appointmentsTable.setObjectName("appointmentsTable")
        self.patientsTab = QtWidgets.QWidget()
        self.patientsTab.setObjectName("patientsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.patientsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.patientsTable = QtWidgets.QTableView(self.patientsTab)
        self.patientsTable.setObjectName("patientsTable")
        self.verticalLayout.addWidget(self.patientsTable)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.addPatientBtn = QtWidgets.QPushButton(self.patientsTab)
        self.addPatientBtn.setObjectName("addPatientBtn")
        self.horizontalLayout_3.addWidget(self.addPatientBtn)
        self.deletePatientBtn = QtWidgets.QPushButton(self.patientsTab)
        self.deletePatientBtn.setObjectName("deletePatientBtn")
        self.horizontalLayout_3.addWidget(self.deletePatientBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.appointmentsTable.addTab(self.patientsTab, "")
        self.doctors = QtWidgets.QWidget()
        self.doctors.setObjectName("doctors")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.doctors)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doctorsTable = QtWidgets.QTableView(self.doctors)
        self.doctorsTable.setObjectName("doctorsTable")
        self.verticalLayout_2.addWidget(self.doctorsTable)
        self.appointmentsTable.addTab(self.doctors, "")
        self.appointments = QtWidgets.QWidget()
        self.appointments.setObjectName("appointments")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.appointments)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.appointments)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.appointmentsTable.addTab(self.appointments, "")
        self.horizontalLayout_2.addWidget(self.appointmentsTable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.appointmentsTable.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addPatientBtn.setText(_translate("MainWindow", "Добавить"))
        self.deletePatientBtn.setText(_translate("MainWindow", "Удалить"))
        self.appointmentsTable.setTabText(self.appointmentsTable.indexOf(self.patientsTab), _translate("MainWindow", "Пациенты"))
        self.appointmentsTable.setTabText(self.appointmentsTable.indexOf(self.doctors), _translate("MainWindow", "Врачи"))
        self.appointmentsTable.setTabText(self.appointmentsTable.indexOf(self.appointments), _translate("MainWindow", "Записи"))
